# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-14 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BManager',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=30)),
                ('ephone', models.CharField(max_length=30)),
                ('mpwd', models.CharField(max_length=30)),
                ('mIsDelete', models.BooleanField(default=False)),
                ('eCreatedTime', models.DateTimeField(auto_now_add=True)),
                ('m_img', models.ImageField(upload_to='imgs')),
            ],
            options={
                'db_table': 't_manager',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=100)),
                ('publishing', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('pubTime', models.DateField()),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('b_img', models.ImageField(upload_to='imgs')),
            ],
            options={
                'db_table': 't_book',
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('bc_id', models.AutoField(primary_key=True, serialize=False)),
                ('bcname', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 't_bookcategory',
            },
        ),
        migrations.CreateModel(
            name='BookRack',
            fields=[
                ('br_id', models.AutoField(primary_key=True, serialize=False)),
                ('brname', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 't_bookrack',
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('bor_id', models.AutoField(primary_key=True, serialize=False)),
                ('bTime', models.DateTimeField(auto_now_add=True)),
                ('rTime', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow', to='booklib.Book')),
            ],
            options={
                'db_table': 't_borrow',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('gname', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 't_grade',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 't_major',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 't_position',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('subname', models.CharField(max_length=30)),
                ('bookcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='booklib.BookCategory')),
            ],
            options={
                'db_table': 't_subject',
            },
        ),
        migrations.CreateModel(
            name='Unkownbook',
            fields=[
                ('un_id', models.AutoField(primary_key=True, serialize=False)),
                ('unkname', models.CharField(max_length=100, unique=True)),
                ('unkauthor', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 't_unkownbook',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=30)),
                ('sphone', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('spwd', models.CharField(max_length=30)),
                ('sIsDelete', models.BooleanField(default=False)),
                ('sCreatedTime', models.DateTimeField(auto_now_add=True)),
                ('s_img', models.ImageField(upload_to='imgs')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='booklib.Grade')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='booklib.Major')),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('uc_id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 't_usercategory',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='usca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='booklib.UserCategory'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow', to='booklib.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='bookrack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='booklib.BookRack'),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='booklib.Subject'),
        ),
        migrations.AddField(
            model_name='bmanager',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmanager', to='booklib.Position'),
        ),
    ]
